### ISSUE TITLE
Understanding Mongo, JWT & CLoud

### ISSUE THREAD

**Issue by hungrybearpls** [rohitbakoliya/sieve.ai#7]
Hello, 

This is not an issue, but more a question regarding the ID for the env file. Where am I to find the mongo uri, google client id, google client secret and JWT Tokens? Is this all for setting up separate servers where the data is stored?

Sorry if this is a very beginner question.

**Comment by rohitbakoliya** [comment]
Hi,
For the mongo URI, you can refer [this](https://www.mongodb.com/basics/mongodb-atlas-tutorial)
> Actually, the mongo URI is a connection string required to connect with the database. 
> For eg. it looks like this:
![image](https://user-images.githubusercontent.com/46809038/154791461-2502ff7f-e382-4bb7-8219-7dc51736eeec.png)

For setting up Google Oauth refer to this [artical](https://docs.bettyblocks.com/en/articles/1012838-setting-up-google-oauth-2-0-authentication)

JWT token secret can be anything until it is private. So you can use any random string.
